setUserPreferences
notificationapi-com/notificationapi-node-server-sdk pull request #15
Opened 2021-12-20 18:33 UTC by mbasadi

setUserPreferences

2021-12-20 18:37 UTC, mbasadi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Back-end SDK](https://trello.com/c/6NrSqBQK/568-update-back-end-sdk)

2021-12-20 19:02 UTC, sahandseifi requested changes

2021-12-20 19:02 UTC, sahandseifi commented on src/__tests__/index.test.ts
> +      expect(axiosMock.history.post[0].url).toEqual(
With subNotificationId, you are probably not too concerned with the URL. You probably just want to check that the parameter is sent correctly. So feel free to simplify the test to only check what you intend to check.

2021-12-20 20:17 UTC, mbasadi commented
@sahandseifi Thanks for your comments. Please check again.

2021-12-21 14:59 UTC, sahandseifi requested changes

2021-12-21 14:59 UTC, sahandseifi commented on src/__tests__/index.test.ts
> +    expect(axiosMock.history.post[0].data).toEqual(
When asserting completely different things, separate test cases.

Check the retract tests

2021-12-21 14:59 UTC, sahandseifi commented on src/interfaces.ts
> +export interface SetUserPreferences {
SetUserPreferences sounds like the name of a function. Please rename.

2021-12-21 16:04 UTC, merged